//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.25 at 01:34:42 PM CST 
//

package org.daoefang.b2c.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "oldPassword", "newPassword",
		"confirmPassword", "email" })
@XmlRootElement(name = "password")
public class Password {

	protected String oldPassword;
	protected String newPassword;
	protected String confirmPassword;
	protected String email;
	@XmlAttribute(name = "name")
	protected String name;

	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String value) {
		this.oldPassword = value;
	}

	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String value) {
		this.newPassword = value;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String value) {
		this.confirmPassword = value;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String value) {
		this.email = value;
	}

	public String getName() {
		return name;
	}

	public void setName(String value) {
		this.name = value;
	}

}
